In [1]:
import pandas as pd
import numpy as np

In [2]:
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")

Pandas version: 2.3.3
Numpy version: 2.3.5


In [6]:
df=pd.read_csv('healthcare_basic_dataset.csv')
df.head(5)

Patient_ID  Age  Gender   BMI  Blood_Pressure Diabetes
0           1   25    Male  22.5             120       No
1           2   34  Female  24.1             118       No
2           3   45    Male  26.3             130      Yes
3           4   29  Female  23.8             115       No
4           5   50    Male  27.5             135      Yes

In [7]:
#display the rows and column
df.shape


(20, 6)

In [8]:
#Shows the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Patient_ID      20 non-null     int64  
 1   Age             20 non-null     int64  
 2   Gender          20 non-null     object 
 3   BMI             20 non-null     float64
 4   Blood_Pressure  20 non-null     int64  
 5   Diabetes        20 non-null     object 
dtypes: float64(1), int64(3), object(2)
memory usage: 1.1+ KB


In [11]:
df.describe()

<bound method NDFrame.describe of     Patient_ID  Age  Gender   BMI  Blood_Pressure Diabetes
0            1   25    Male  22.5             120       No
1            2   34  Female  24.1             118       No
2            3   45    Male  26.3             130      Yes
3            4   29  Female  23.8             115       No
4            5   50    Male  27.5             135      Yes
5            6   41  Female  25.9             128       No
6            7   38    Male  24.7             122       No
7            8   60  Female  29.1             140      Yes
8            9   55    Male  28.4             138      Yes
9           10   33  Female  23.5             117       No
10          11   27    Male  22.9             119       No
11          12   48  Female  26.8             132      Yes
12          13   52    Male  27.9             136      Yes
13          14   36  Female  24.3             121       No
14          15   44    Male  25.6             127       No
15          16   58  F

In [12]:
df.isnull().sum()

Patient_ID        0
Age               0
Gender            0
BMI               0
Blood_Pressure    0
Diabetes          0
dtype: int64

In [13]:
df=pd.read_csv('student_performance_100.csv')
df.shape

(100, 8)

In [14]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Subject', 'Marks', 'Attendance',
       'Result'],
      dtype='object')

In [16]:
df['Marks'].isnull().sum()

np.int64(10)

In [17]:
len(df)

100

In [20]:
df['Gender'].value_counts()['F']

np.int64(50)

In [22]:
rows_with_nulls=df[df.isnull().any(axis=1)]
rows_with_nulls

Student_ID   Name  Age Gender  Subject  Marks  Attendance Result
4          105  Ankit   21      M  Physics    NaN        60.0   Fail
7          108  Kavya   19      F  Physics   82.0         NaN   Pass
14         115  Ankit   21      M  Physics    NaN        60.0   Fail
17         118  Kavya   19      F  Physics   82.0         NaN   Pass
24         125  Ankit   21      M  Physics    NaN        60.0   Fail
27         128  Kavya   19      F  Physics   82.0         NaN   Pass
34         135  Ankit   21      M  Physics    NaN        60.0   Fail
37         138  Kavya   19      F  Physics   82.0         NaN   Pass
44         145  Ankit   21      M  Physics    NaN        60.0   Fail
47         148  Kavya   19      F  Physics   82.0         NaN   Pass
54         155  Ankit   21      M  Physics    NaN        60.0   Fail
57         158  Kavya   19      F  Physics   82.0         NaN   Pass
64         165  Ankit   21      M  Physics    NaN        60.0   Fail
67         168  Kavya   19      F  Physics   82.0         NaN   Pass
74         175  Ankit   21      M  Physics    NaN        60.0   Fail
77         178  Kavya   19      F  Physics   82.0         NaN   Pass
84         185  Ankit   21      M  Physics    NaN        60.0   Fail
87         188  Kavya   19      F  Physics   82.0         NaN   Pass
94         195  Ankit   21      M  Physics    NaN        60.0   Fail
97         198  Kavya   19      F  Physics   82.0         NaN   Pass

In [24]:
null_rows_count=df[df.isnull().any(axis=1)].shape[0]
null_rows_count

20

In [27]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[8,9,1,0]])
print(arr1)


[[1 2 3 4]
 [5 6 7 8]
 [8 9 1 0]]


In [29]:
#accessing a single value (row 1, col 2)
print(arr1[1,2])

7


In [31]:
print(arr1[1][2])

7


In [32]:
#slicing a submatrix from top-left 2x2
#matrix[wors,columns]

sub=arr1[0:2,0:2]
print(sub)

[[1 2]
 [5 6]]
