In [1]:
import numpy as np
import pandas as pd

In [9]:
x = np.array([
    [10, 12, 14, 16, 18],
    [20, 22, 24, 26, 28],
    [30, 32, 34, 36, 38],
    [40, 42, 44, 46, 48]
])


array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [36]:
#difference between x and print(x)
x
print(x)

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [7]:
#shape
x.shape

(4, 5)

In [21]:
x.dtype

dtype('int64')

In [23]:
x.size

20

In [34]:
sum(x)
x.sum()

np.int64(580)

In [38]:
even_arr=x[x%2==0]
print(even_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [40]:
even_arr.size


20

In [41]:
x[:,2]

array([14, 24, 34, 44])

In [42]:
x[1]

array([20, 22, 24, 26, 28])

In [44]:
temp=x[1:3,2:5]
print(temp)


[[24 26 28]
 [34 36 38]]


In [46]:
x[x>30]=-1
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [48]:
x[3]=[1,2,3,4,5]
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [ 1  2  3  4  5]]


In [50]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])




In [51]:
temp = scores[scores<130]
print(temp)

[126 115]


In [53]:
Statira_scores=scores[names=="Statira"]
print(Statira_scores)

[115 141]


In [60]:
scores[names=="Roxana"]+=10
print(scores)

[136 115 140 141 142]


In [1]:
import pandas as pd
data = {
    "Population": [138000, 33100, 14442, 67886],
    "Capital": ["New Delhi", "Washington D.C.", "Beijing", "Paris"]
}

countries_df = pd.DataFrame(
    data,
    index=["India", "United States", "China", "France"]
)

print(countries_df)


               Population          Capital
India              138000        New Delhi
United States       33100  Washington D.C.
China               14442          Beijing
France              67886            Paris


In [4]:
countries_df.head()

Population          Capital
India              138000        New Delhi
United States       33100  Washington D.C.
China               14442          Beijing
France              67886            Paris

In [5]:
countries_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, India to France
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Population  4 non-null      int64 
 1   Capital     4 non-null      object
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes


In [6]:
countries_df.loc["India", "Population"]


np.int64(138000)

In [7]:
countries_df[countries_df["Population"] > 50000]


Population    Capital
India       138000  New Delhi
France       67886      Paris

In [8]:
countries_df["GDP"] = [3.7, 25.5, 17.7, 3.0]  


In [9]:
countries_df

Population          Capital   GDP
India              138000        New Delhi   3.7
United States       33100  Washington D.C.  25.5
China               14442          Beijing  17.7
France              67886            Paris   3.0

In [11]:
countries_df.rename(columns={"Population": "Population_Count"}, inplace=True)
countries_df


Population_Count          Capital   GDP
India                    138000        New Delhi   3.7
United States             33100  Washington D.C.  25.5
China                     14442          Beijing  17.7
France                    67886            Paris   3.0

In [12]:
countries_df.drop(columns=["Capital"], inplace=True)
countries_df

Population_Count   GDP
India                    138000   3.7
United States             33100  25.5
China                     14442  17.7
France                    67886   3.0

In [14]:
countries_df.sort_values(by="Population_Count",inplace=True)
countries_df

Population_Count   GDP
China                     14442  17.7
United States             33100  25.5
France                    67886   3.0
India                    138000   3.7

In [15]:
average_population = countries_df["Population_Count"].mean()
print(average_population)


63357.0
