In [5]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [40]:
text =[
    "i am learning deep learning",
    "i like deep learning",
    "deep learning is fun to learn",
    "i also like machine learning"
]

In [41]:
tokenizer =Tokenizer()
tokenizer.fit_on_texts(text)

In [42]:
sequences = tokenizer.texts_to_sequences(text)
print(sequences)

[[2, 5, 1, 3, 1], [2, 4, 3, 1], [3, 1, 6, 7, 8, 9], [2, 10, 4, 11, 1]]


In [43]:
# Creating input and output pairs
X = []
y = []
for seq in sequences:
  for i in range(1, len(seq)):
    X.append(seq[:i])
    y.append(seq[i])

In [44]:
# Pad sequences
X = pad_sequences(X)
y = np.array(y)

In [45]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  5]
 [ 0  0  2  5  1]
 [ 0  2  5  1  3]
 [ 0  0  0  0  2]
 [ 0  0  0  2  4]
 [ 0  0  2  4  3]
 [ 0  0  0  0  3]
 [ 0  0  0  3  1]
 [ 0  0  3  1  6]
 [ 0  3  1  6  7]
 [ 3  1  6  7  8]
 [ 0  0  0  0  2]
 [ 0  0  0  2 10]
 [ 0  0  2 10  4]
 [ 0  2 10  4 11]]


In [46]:
print(y)

[ 5  1  3  1  4  3  1  1  6  7  8  9 10  4 11  1]


In [47]:
vocab_size = len(tokenizer.word_index) +1 

In [48]:
vocab_size

12

In [49]:
# Build RNN Model
model = Sequential([
    Embedding(vocab_size, 10, input_length=X.shape[1]),
    SimpleRNN(32),
    Dense(vocab_size, activation='softmax')
])

C:\Users\rinku\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [50]:
model.compile(loss="sparse_categorical_crossentropy",
    optimizer="adam")

In [51]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 2.4890
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 2.4773
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 2.4657
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 2.4540
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - loss: 2.4423
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 2.4304
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 2.4183
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 2.4059
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 2.3931
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 2.3797
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 2.3659
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 2.3515
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 2.3365
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 2.3208
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 2.3044
Epoch 16/100
1/